### PR TITLE
Update diacritics mapping according to github.com/diacritics/database

### PR DESCRIPTION
**Pull request by thomasgalliker**

### CODE REVIEW

**Comment by pavanupb** [comment]
@thomasgalliker When would this PR be merged. I am waiting for the German Umlaut corrected Mapping. 

Thanks!

**Comment by thomasgalliker** [comment]
Oughhh. I‘m sorry for the delay. I gonna merge it asap.

**Comment by thomasgalliker** [comment]
@pavanupb you'll find the nuget pre-release here: https://www.nuget.org/packages/Diacritics/3.2.21207.2-pre 
I think there is some more work to be done before I can release the next stable nuget. Please let me know if anything goes wrong with this 3.2.x version.

**Comment by pavanupb** [comment]
@thomasgalliker Thanks for pre-release.

**Pull request merged**
