### PR TITLE
Add missing mapping in Vietnamese [Đ,đ] to [D,d]

### PR DESCRIPTION
**Pull request by ltduy**
Đ & đ should be updated to D & d in Vietnamese.

### CODE REVIEW

**Comment by thomasgalliker** [comment]
Thanks! Did you check the other vietnamese characters? Are they correct and complete? I will merge this asap.

**Comment by ltduy** [comment]
Hi Thomas, 

Thanks for quick response. Yes, I checked other cases and add unit test cases for rest of them as well.

However, there are some Vietnamese keyboard using Non Spacing Mark for diacritics, I have to remove these characters to handle these cases, I add sample code below. Do you think Diacritics.NET can resolve this case by any chances?

https://dotnetfiddle.net/H493ma

Thanks,
Duy

**Comment by ltduy** [comment]
Some how the dotnetfiddle does keep original string, I put screenshot here in case it does not work from your side

var problematicString = "ĐỖ THỊ LẬP";

image

**Comment by thomasgalliker** [comment]
I will look at the code and ask you again. Thanks for your effort!

**Comment by ltduy** [comment]
Hi @thomasgalliker,

Please ignore non spacing mark problem above, this PR scope should be enough for Vietnamese. Regarding to non spacing mark problem, it can be resolved by normalizing the string. This PR should be good to merge if you don't have any more questions.

https://dotnetfiddle.net/MPB9jh

Regards,
Duy

**Comment by ltduy** [comment]
@thomasgalliker unit test project is using core 3.1 which is no longer support by current MS Hosted agent. I pushed another commit to upgrade to .net 6.

**Comment by ltduy** [comment]
Hi @thomasgalliker, is there anything else you like to update?

**Comment by thomasgalliker** [comment]
Im sorry for the huge delay! Thanks for your contribution.

**Pull request merged**
